// <auto-generated />
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("userBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "user1",
                            userBalance = 1000.00m
                        },
                        new
                        {
                            Id = 2,
                            UserId = "user2",
                            userBalance = 2000.00m
                        },
                        new
                        {
                            Id = 3,
                            UserId = "user3",
                            userBalance = 3000.00m
                        },
                        new
                        {
                            Id = 4,
                            UserId = "user4",
                            userBalance = 4000.00m
                        },
                        new
                        {
                            Id = 5,
                            UserId = "user5",
                            userBalance = 5000.00m
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PortfolioId = 1,
                            Quantity = 10,
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            PortfolioId = 2,
                            Quantity = 20,
                            StockId = 2
                        },
                        new
                        {
                            Id = 3,
                            PortfolioId = 3,
                            Quantity = 30,
                            StockId = 3
                        },
                        new
                        {
                            Id = 4,
                            PortfolioId = 4,
                            Quantity = 40,
                            StockId = 4
                        },
                        new
                        {
                            Id = 5,
                            PortfolioId = 5,
                            Quantity = 50,
                            StockId = 5
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 100.00m,
                            Symbol = "ABC"
                        },
                        new
                        {
                            Id = 2,
                            Price = 200.00m,
                            Symbol = "DEF"
                        },
                        new
                        {
                            Id = 3,
                            Price = 300.00m,
                            Symbol = "GHI"
                        },
                        new
                        {
                            Id = 4,
                            Price = 400.00m,
                            Symbol = "JKL"
                        },
                        new
                        {
                            Id = 5,
                            Price = 500.00m,
                            Symbol = "MNO"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PortfolioItem", b =>
                {
                    b.HasOne("Entities.Concrete.Portfolio", null)
                        .WithMany("Items")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.Portfolio", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
